# Generated by Django 4.2.4 on 2023-08-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_sociallink_alter_about_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.URLField(),
        ),
    ]
